language: python
python:
    - "2.7"
    - "3.6"
before_install:
 - sudo apt-get update -qq
install:
    - pip install .
    - pip install -r requirmeents_dev.txt
script: python -m pytest -vv --cov-report term-missing --cov korg tests/test_*
# after_success:
#   # Report coverage results to coveralls.io
#   - pip install coveralls
#   - coveralls
